name: Get Vidio Token
on:
  push:
    branches:
      - main

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Ganti 'x' dengan versi Python yang diinginkan
      
      - name: Run Python Script
        run: |
          python -m pip install requests
          python - << EOF
          import requests
          import json

          tv = input('Masukkan ID TV: ')
          tokke = 'https://www.vidio.com/live/{}/tokens'.format(tv)

          headers = {
              'Content-Type': 'application/x-www-form-urlencoded',
              'charset': 'utf-8'
          }

          response = requests.post(tokke, headers=headers)
          result = response.json()
          token = result.get('token', '')

          print(token)
          EOF
