name: Get Vidio Token
on:
  push:
    branches:
      - main

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Ganti 'x' dengan versi Python yang diinginkan

      - name: Install Requests
        run: python -m pip install requests

      - name: Run Python Script
        env:
          TV_ID: 204
        run: |
          python << EOF > live/204.json
          import os
          import requests
          import json

          tv = os.getenv('TV_ID')

          tokke = 'https://www.vidio.com/live/' + tv + '/tokens'

          headers = {
              'Content-Type': 'application/x-www-form-urlencoded',
              'charset': 'utf-8'
          }

          response = requests.post(tokke, headers=headers)
          result = response.json()
          token = result.get('token', '')

          with open('live/204.json', 'w') as file:
              json.dump(result, file)

          print(token)
          EOF
