name: Get Vidio Token
on:
  push:
    branches:
      - main

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Ganti 'x' dengan versi Python yang diinginkan

      - name: Set Environment Variable
        run: echo "TV_ID=<ID_TV>" >> $GITHUB_ENV
        env:
          TV_ID: ${{ secrets.ID_TV }}

      - name: Install Dependencies
        run: python -m pip install requests

      - name: Run Python Script
        run: python get_token.py
